customhost = "employee.cpmb7rjgexnk.ap-south-1.rds.amazonaws.com"
customuser = "admin"
custompass = "mysql123"
customdb = "employee"
custombucket = "mywebsitebucketemployee"
customregion = "ap-south-1"
